### ISSUE TITLE
Hosting 

### ISSUE THREAD

**Issue by braidn** [treymiller/eMG-frontend#3]
Google, find some ideas and dump them in here @jordancauley and @treymiller 

http://nodejs-cloud.com/

**Comment by jdcauley** [comment]
Do you think PAAS is the best most effective way to go?

**Comment by treymiller** [comment]
Do you think it's not? What are the alternatives? Are we talking frontend or backend? Both?

**Comment by ghost** [comment]
Both

**Comment by treymiller** [comment]
I don't think I'm equipped to answer the question. Is there a way to estimate/predict resource requirements at various usage levels? 

Seems like the frontend is never likely to go under heavy load for long. Maybe we get Fireballed or we make the frontpage of HN…what are the odds of that? 1 in a million? (So you're tellin' me there's a chance…) Mostly, just steady web traffic to a mostly-static site.

On the backend, things should scale up smoothly, right? Less likely to get bursts for a few minutes…

Are these assumptions correct, and what do they imply about which choice is right for each?

**Comment by braidn** [comment]
Pass might not be the best option and Heroku dynos are shit when it comes to performance. However, we or I would be spinning my wheels otherwise. Maybe dokku digital ocean

**Comment by treymiller** [comment]
For what it's worth, we'll put everything on my credit card, and while I don't want to throw money away, I even more don't want to choose the "cheapest" option up-front if a slightly pricier, but much more flexible/scalable/etc. option would be better.

I know we need to consider dev environment + production and probably some other stuff, so let's keep talking...

Trey
Triad Tech Services
336.912.2110
triadts.com

**Comment by braidn** [comment]
@treymiller true but, I would like to keep costs low for now (as close to none as possible).

**Comment by treymiller** [comment]
Me too, and I appreciate that, but let's just commit to going with the free/cheap option ONLY when it's also the best option. 

Trey
Triad Tech Services
336.912.2110
triadts.com

**Comment by ghost** [comment]
I'm in favor of DO with Dokku I'm not sure we can get cheaper. We can run a dev an initial production an db server for 15 which is a lot cheaper than where most other options start

**Comment by treymiller** [comment]
I haven't stopped thinking about eMailGrouper for more than 5 minutes since Friday afternoon, but a little whole ago I poured a whiskey and started watching the first episode of Silicon Valley free on YouTube and it is awesome.

**Comment by treymiller** [comment]
I'll go with your recommendation unless Braden speaks up by lunch time.

Trey
Triad Tech Services
336.912.2110
triadts.com

**Comment by treymiller** [comment]
You're not concerned about this?:

> Dokku is under heavy development, and undergoes changes from one release to the next. We recommend that you regularly check the Dokku page on GitHub if you plan on deploying production application.

**Comment by braidn** [comment]
I am very concerned about this actually. As I age I become more resistant to be on the bleeding edge. For instance, my rails projects are stuck on 3.2.x (4.2 released on Wednesday) because that version is nutty stable and I don't have to worry about upgrades shooting me in the foot. 

So here is kind of what I would like to see for a deployment platform for Node: cloud66.com or shellycloud.com. @jdcauley do you understand what's going on with these offerings? Do you know of anything like this for Node?

**Comment by ghost** [comment]
So you want to use something like nodejitsu?

**Comment by treymiller** [comment]
Braden do you currently use either of the ones you mentioned?

The pricing seems reasonable to me, but I'm not sure I understand how performance and cost scale. 

Trey
Triad Tech Services
336.912.2110
triadts.com

**Comment by treymiller** [comment]
Also, how does dev fit into this?

I assume we setup MX records for dev.emailgrouper.com and just test amongst ourselves...but I'm sure that's about 1/100th of the equation. 

Trey
Triad Tech Services
336.912.2110
triadts.com

**Comment by braidn** [comment]
I use cloud66 and really enjoy it. They are handling this whole heartbleed thing extremely well.

**Comment by jdcauley** [comment]
They haven't added node support yet have they?

**Comment by treymiller** [comment]
? http://www.joyent.com/products/support-nodejs
? https://devcenter.heroku.com/articles/getting-started-with-nodejs

We have SW discount codes for AWS ($100 off) and Google Cloud Platform (apply and if selected you get $500 credit)...seems like we should at least consider AWS...

**Comment by braidn** [comment]
AWS can be more expensive and just as much of a bear as DigitalOcean.

**Comment by treymiller** [comment]
OK, but "can be more expensive" is a squishy phrase…can we measure/predict how this needs to scale, and do a simple cost comparison? Tell me the variables and estimated of # of servers (separate instance for frontend, dev, production, db?) / CPU / RAM / Disk, etc. and I'll pull prices together.

It seems certain that we won't outgrow AWS, and once we've made our first $3 or $3,000, we can maybe start to predict where some costs are going to outpace others…Let me help with the business portion of this decision - you guys just say what's the place and why...

Trey
Triad Tech Services
336.912.2110
triadts.com

**Comment by treymiller** [comment]
It's about f#&king time!!!!


Trey
Triad Tech Services
336.912.2110
triadts.com
